[package]
name = "piperchat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gst = { version = "0.19.1", package = "gstreamer" }
gst-video = { version = "0.19.0", package = "gstreamer-video" }
gtk4 =  "0.5.1"
gtk = "0.16.0"

[build-dependencies]
glib-build-tools = "0.16.3"
